### ISSUE TITLE
FunAttrib abandoned?

### ISSUE THREAD

**Issue by owinter92** [PetrKryslUCSD/MeshCore.jl#4]
Is FunAttrib abandoned or WIP/TODO?

**Comment by PetrKryslUCSD** [comment]
No, indeed it is neither. It is both tested, and used in downstream package (MeshSteward).

**Comment by owinter92** [comment]
It is tested but I cannot find any usage of it in MeshSteward or anywhere else.

**Comment by PetrKryslUCSD** [comment]
You are right, I think I intended to write an example of its use in the tutorials, but apparently that didn't happen. Nevertheless, it is useful to have a functional version of an attribute. If for nothing else than to provide attributes which are simply a constant value. Lots of storage can saved that way.

**Comment by owinter92** [comment]
Hi, I am sorry for a delayed answer. 

>Nevertheless, it is useful to have a functional version of an attribute.

Indeed it is.

I was just little confused given I didn't found any usage of it.

**Comment by PetrKryslUCSD** [comment]
Imagine you have a logically rectangular grid in three dimensions. The coordinates can then be expressed implicitly, through a function. They don't need to be stored in an array. That was the thinking behind the function attribute. When I have some time I will put together a tutorial how to do that.

**Comment by PetrKryslUCSD** [comment]
Check out MeshTutor.jl, tutorial 9. The geometry is defined implicitly using the function attribute.

**Comment by PetrKryslUCSD** [comment]
Thanks again for alerting me to the missing functionality. Is it okay to close?

**Comment by owinter92** [comment]
Yes, thanks for the tutorial.
