### ISSUE TITLE
Oriented incidence relations

### ISSUE THREAD

**Issue by apalha** [PetrKryslUCSD/MeshCore.jl#8]
I am working with finite element basis functions that require knowledge of the orientation of the geometric objects to which they are associated to. Something similar to what takes place in Raviart-Thomas and Nedelec elements.

I was unable to understand if this is a functionality that already exists or not. Essentially, I would like to be able to have:

Incidence relations with signed values such that if the incidence relation (n, 1) contains and - sign, it means that the edge appears in the element with the opposite direction in which it is defined. 

Is this already available but in another way? 

Thank you for your help.

Kind regards,

-artur palha

**Comment by PetrKryslUCSD** [comment]
Yes, for instance edges are oriented entities. Perhaps this paper will help? https://github.com/PetrKryslUCSD/MeshCore.jl/blob/master/docs/src/concepts/mesh-topo-v6.pdf

**Comment by PetrKryslUCSD** [comment]
![image](https://github.com/PetrKryslUCSD/MeshCore.jl/assets/9855832/7acdd592-4524-4f60-860a-f161d2da5e25)

**Comment by apalha** [comment]
Thank you @PetrKryslUCSD !

I just tested it with a two-element triangular mesh, and I can see the negative values.

I tried this code to check it in 3D

```julia
# Tets
xys = [
    0.0 0.0 0.0
    0.0 1.0 0.0
    0.0 0.0 1.0
    0.0 1.0 1.0
    1.0 0.0 0.0
]

connectivity = [
    1 2 3 5
    2 4 3 5
]

# Convert input data into MeshCore data structures
geo_dim, coordinate_type = size(xys, 2), MeshCore.eltype(xys)
xys_meshcore =  MeshCore.VecAttrib([SVector{geo_dim, coordinate_type}(xys[i, :]) for i in 1:size(xys, 1)])


# Setup the vertices in MeshCore
n_vertices = length(xys_meshcore)
vertices = MeshCore.ShapeColl(MeshCore.P1, n_vertices, "vertices")
vertices.attributes["geom"] = xys_meshcore

# Setup elements in MeshCore
n_elements = size(connectivity, 1)
elements = MeshCore.ShapeColl(MeshCore.T4, n_elements)
mesh = MeshCore.IncRel(elements, vertices, connectivity)  # which is also the (2, 0) incidence relation here

# Compute the other required incidence relations: (3, 2)
faces = MeshCore.ir_skeleton(mesh)
element2face = MeshCore.ir_bbyfacets(mesh, faces)

# Compute the other required incidence relations: (3, 1)
edges = MeshCore.ir_skeleton(faces)
element2edge = MeshCore.ir_bbyridges(mesh, edges)
```
All works fine until the last line

```julia
element2edge = MeshCore.ir_bbyridges(mesh, edges)
```
I debugged it and the offending line is in function:
```julia
function IncRel(
    left::ShapeColl{LEFT},
    right::ShapeColl{RIGHT},
    data::Matrix{MT},
    name::String
) where {LEFT<:AbsShapeDesc, RIGHT<:AbsShapeDesc, MT}
    _v = [SVector{nvertices(left.shapedesc)}(data[idx, :]) for idx in 1:size(data, 1)]  # --> offending line
    IncRel(left, right, _v, name, true)
end
```
Maybe I misunderstand it, but _v is the incidence relation between cells and edges (in this case). But the rows of `_v`, contain a static vector of dimension `nvertices(left.shapedesc)`, which is the number of vertices in the tet. Should it not be `nridges(left.shapedesc)`?

**Comment by PetrKryslUCSD** [comment]
Thank you for catching a bug: the data vector was incorrectly dimensioned. A new version has been registered (1.3.5). Your example (with minor additions):
```
using MeshCore.Exports
using StaticArrays 

# Tets
xys = [
    0.0 0.0 0.0
    0.0 1.0 0.0
    0.0 0.0 1.0
    0.0 1.0 1.0
    1.0 0.0 0.0
]

connectivity = [
    1 2 3 5
    2 4 3 5
]

# Convert input data into MeshCore data structures
geo_dim, coordinate_type = size(xys, 2), eltype(xys)
xys_meshcore =  VecAttrib([SVector{geo_dim, coordinate_type}(xys[i, :]) for i in axes(xys, 1)])


# Setup the vertices in MeshCore
n_vertices = length(xys_meshcore)
vertices = ShapeColl(P1, n_vertices, "vertices")
vertices.attributes["geom"] = xys_meshcore

# Setup elements in MeshCore
n_elements = size(connectivity, 1)
elements = ShapeColl(T4, n_elements)
mesh = IncRel(elements, vertices, connectivity)  # which is also the (3, 0) incidence relation here

# Compute the other required incidence relations: (3, 2)
faces = ir_skeleton(mesh)
element2face = ir_bbyfacets(mesh, faces)

# Compute the other required incidence relations: (3, 1)
edges = ir_skeleton(faces)
element2edge = ir_bbyridges(mesh, edges)

@show summary(element2edge)
@show getv(element2edge)

nothing
```
now produces
```
julia> summary(element2edge) = "bbr: shapes = 2 x T4, shapes = 9 x L2"
getv(element2edge) = SVector{6, Int64}[[-3, 4, -1, -8, -6, 2], [6, -7, -5, -8, -9, 4]]
```

**Comment by apalha** [comment]
Dear @PetrKryslUCSD , thank you!

One final question. I am interested in space-time finite element formulations. How complex do you think it would be to extend these ideas to 4D meshes?

**Comment by PetrKryslUCSD** [comment]
Do you mean would the mesh representation work with 4 dimensions?
I think it would, but one would have to define appropriate shape descriptors. The current ones are only for three dimensional space.

**Comment by apalha** [comment]
Thank you for your answer. I was considering doing some exploratory work with an MSc student.
